### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by wonea** [Schlechtwetterfront/snipp#3]
I pin Snipp to my taskbar, but because the application executable doesn't have a set icon I get this.

![image](https://user-images.githubusercontent.com/557192/28930303-76ef1310-786a-11e7-8e0c-6e3731a8308b.png)

**Comment by Schlechtwetterfront** [comment]
Added the icon in 8fade4504a68718e260f347f8d031bd5ca36f6db. Thanks for the suggestion, check out the latest release including this change.
