### ISSUE TITLE
Don't snipp if the same as last

### ISSUE THREAD

**Issue by wonea** [Schlechtwetterfront/snipp#6]
Don't snipp if the same as last snipp, also if it exists perhaps push it to the top?

Hitting CTRL+C multiple times on the same things duplicates it.

**Comment by wonea** [comment]
Here is an example

![image](https://user-images.githubusercontent.com/557192/31810859-3617209c-b575-11e7-9de3-f3c49a82628c.png)

**Comment by Schlechtwetterfront** [comment]
I just tested with the latest version (which you seem to have, too, though) and I don't get any duplicates.

**Comment by wonea** [comment]
Yes, I'm on the latest version.

Found the problem. Just cleared all the previous results, and tried copying again. No duplicates! 👍
